version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "5000:5000"
    nginx:
        restart: always
        build:
            context: ./nginx
        volumes:
            - ./nginx/log:/var/log/nginx
        ports:
            - "8080:80"